version: '3'
services:
  account-service:
    image: accounts 
    container_name: account-service-test

  token-management-service:
    image: token-management-service
    container_name: token-management-service-test

  transaction-service:
    image: transactions
    container_name: transaction-service-test

  rest-api:
    image: rest-api
    container_name: rest-api-test
    ports:
      - "8080:8080"

  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container-test
    ports:
      - "5672:5672"

