version: '3'
services:
  account-service:
    image: accounts 
    container_name: account-service

  token-management-service:
    image: token-management-service
    container_name: token-management-service

  transaction-service:
    image: transactions
    container_name: transaction-service

  rest-api:
    image: rest-api
    container_name: rest-api
    ports:
      - "8080:8080"

  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container

